### ISSUE TITLE
Using the zoom often freeze the interface

### ISSUE THREAD

**Issue by VosaXalo** [flathub/com.github.junrrein.PDFSlicer#11]
I have found out that the zoom functionality often freezes the PDFSlicer interface and I have to kill the process.
I'm using the app on KDE neon 18.04.

**Comment by junrrein** [comment]
Thanks for the report.

I resubmitted this at the central Slicer repo [1], since this also happens in the non-Flatpak version.

[1] https://github.com/junrrein/pdfslicer/issues/58
