### ISSUE TITLE
Use OpenJPEG from the runtime if it's there

### ISSUE THREAD

**Issue by junrrein** [flathub/com.github.junrrein.PDFSlicer#32]
I just noticed there is a shared-module for OpenJPEG in the Flathub repo: https://github.com/flathub/shared-modules/tree/master/openjpeg.

We should see if we can use that instead of what we have now.

**Comment by dreua** [comment]
Just stumbled upon this while trying to debug another build and thought I'd leave the info here: OpenJPEG is not part of shared-modules any more. The [removal commit}(https://github.com/flathub/shared-modules/commit/83be76b6f07d5c5d6cac2d93e09ffc9c1ade07d0) says it's "now in the fdo 20.04 runtime".

**Comment by junrrein** [comment]
@dreua That is useful information to have, thanks!

**Comment by dreua** [comment]
I'm also using Gnome 3.38 runtime and it works, you can just remove the dependency from your flatpak recipe.

**Comment by fedelibre** [comment]
openjpeg is not bundled anymore in the manifest. Fixed in #24 

@junrrein you can close this issue.
