### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by tjanez** [flathub/com.github.junrrein.PDFSlicer#55]
Hi!

It appears the latest released version via Flathub is version 1.8.8 published on Dec 9, 2020.

I've seen some updates since then. Would it make sense to release a new version?

**Comment by hfiguiere** [comment]
![image](https://github.com/flathub/com.github.junrrein.PDFSlicer/assets/114441/e62c2ed7-b820-4cfe-ae35-494c0a3de7c7)


It's already the latest.
